require 'erbt'

desc "test"
task 'test' do
  __erbt("test1")
  print File.read("test1")
  __erbt("test1")
  `echo "" > test1`
  __erbt("test1")
  print File.read("test1")
end

erbt "test1"

desc "clean"
task 'clean' do
  `rm test1`
  `rm test1.backup`
end
